/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Core.JsonHandler;
import Core.Planificador;
import EDD.Lista;
import EDD.Nodo;
import Enums.TipoProceso;
import Modelos.PCB;
import Modelos.Proceso;
import javax.swing.JOptionPane;

/**
 *
 * @author Moises Liota
 */
public class Procesos extends javax.swing.JFrame {

    public static Lista listolista = JsonHandler.readProcesosFromJson("procesos.json");
    public static Lista todos = new Lista();

    public Procesos() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.llenarLista();
    }

    private void llenarLista() {
        Nodo pw = listolista.getpFirst();
        while (pw != null) {
            todos.InsertarFinal(pw.getDato());
            pw = pw.getPnext();
        }
    }

    private boolean validateInputs() {
        try {
           
            if (nombre.getText().isEmpty() || duracion.getText().isEmpty() || cicloT.getText().isEmpty() || duracionExcepcion.getText().isEmpty()) {
                return false;
            }
            
            Integer.valueOf(duracion.getText()); // duracion
            if (this.tipo.getSelectedIndex() == 1) {
                Integer.valueOf(cicloT.getText()); // cicloexcep
                Integer.valueOf(duracionExcepcion.getText()); // duracionexcep
            }
        } catch (NumberFormatException e) {
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        duracion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cicloT = new javax.swing.JTextField();
        duracionExcepcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("Crear Procesos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 190, -1));

        jLabel3.setText("Duracion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel1.add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 190, -1));

        jLabel4.setText("Tipo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPU Bound", "I/O Bound" }));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });
        jPanel1.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 160, -1));

        jLabel5.setText("Ciclo Excepcion");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));
        jPanel1.add(cicloT, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 170, -1));
        jPanel1.add(duracionExcepcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 180, -1));

        jLabel6.setText("Duracion");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        add.setText("Añadir");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 190, -1));

        jButton2.setText("Continuar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 170, -1));

        jButton1.setText("<-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        int ciclo = 1;         // ciclosParaExcepcion
        int duracionExcp = 1;  // ciclosParaSatisfacerExcepcion

        if (this.validateInputs()) {

            // 1) Datos base desde la UI
            final int duracionnt = Integer.parseInt(duracion.getText()); // total de instrucciones
            if (this.tipo.getSelectedIndex() == 1) { // I/O Bound
                ciclo = Integer.parseInt(cicloT.getText());
                duracionExcp = Integer.parseInt(duracionExcepcion.getText());
            } else {
                // Para CPU-Bound no forzamos interrupciones:
                ciclo = 0;
                duracionExcp = 0;
            }

            // 2) Mapear combo a enum
            //    0 = "CPU Bound", 1 = "I/O Bound"  (según tu JComboBox)
            TipoProceso tipoEnum = (this.tipo.getSelectedIndex() == 1)
                    ? Enums.TipoProceso.IO_BOUND
                    : Enums.TipoProceso.CPU_BOUND;

            // 3) Construir el PCB inicial
            PCB pcb = new PCB();
            pcb.setPc(0);
            pcb.setIr(0);
            pcb.setPrioridad(0);
            pcb.setEstado(Enums.EstadoProceso.LISTO);
            pcb.setTiempoEspera(0);

            // 4) Construir el Proceso
            Proceso p = new Proceso();
            p.setId(listolista.getSize());           
            p.setNombre(nombre.getText());
            p.setTipoEnum(tipoEnum);
            p.setInstrucciones(duracionnt);
            p.setCiclosParaExcepcion(ciclo);
            p.setCiclosParaSatisfacerExcepcion(duracionExcp);
            p.setPcb(pcb);

            // 5) Insertar en tus estructuras y refrescar UI
            listolista.InsertarFinal(p);
            todos.InsertarFinal(p);
            
            JOptionPane.showMessageDialog(null, "Proceso añadido correctamente.");

        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "error en los atributos del proceso");
        }
    }//GEN-LAST:event_addActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Bienvenidos v1 = new Bienvenidos();
        listolista.vaciar();
        todos.vaciar();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Procesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Procesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Procesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Procesos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Procesos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField cicloT;
    private javax.swing.JTextField duracion;
    private javax.swing.JTextField duracionExcepcion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
